git add .github/workflows/cd.ymlgit add .github/workflows/cd.ymlname: cd git commit -m "Debug secret" git push 
origin main on: git commit -m "Debug secret" push:
git push origin main    branches: [main]

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.0"

      - name: Run unit tests
        run: go test ./... -cover

      - name: Build prod
        run: scripts/buildprod.sh
      - name: Check secret
        run: |
          if [ -z "${{ secrets.GCP_CREDENTIALS }}" ]; then
            echo "SECRET IS EMPTY!"
          else
            echo "SECRET IS SET"
          fi
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: notely-494816

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and push Docker image
        run: |
          gcloud builds submit \
            --tag us-central1-docker.pkg.dev/notely-494816/notely-ar-repo/notely:${{ github.sha }} \
            .
